[[language]]
name = "python"
language-servers = ["pylsp", "pyright"]
roots = ["pyproject.toml", ".git"]
workspace-lsp-roots = ["src/updater"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = false, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true}
pylsp_mypy = {enabled = false}
rope_autoimport = {enabled = true}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
[language-server.pyright.config]
pyright = { autoImportCompletion = true }
python = { analysis = {autoSearchPaths = true,diagnosticMode = "openFilesOnly", useLibraryCodeForTypes = true,typeCheckingMode = "off"}}

